### ISSUE TITLE
Is it possible to use express-formidable only to parse the bodies of certain POST requests?

### ISSUE THREAD

**Issue by nelson-brochado** [noraesae/express-formidable#1]
I am currently using body parser to parse the bodies of the requests, etc, but I need to upload big files, songs and videos, to the server (so far my requests consisted of text or json), so I thought this module could be useful. I was wondering if it can be used along with body parser and specifically to parse only certain requests, letting body parser continue to work as before.

If it is possible to do it, could you please show a concrete example?

**Comment by noraesae** [comment]
Hi, sorry for the (very) late response as I've not worked on this project personally. express-formidable is just a connect middleware, so how to use is completely up to you.

You can use it for some of routes:

```js
app.post('/no-upload', (req, res) => {
  // ...
});

app.post('/upload', formidable(), (req, res) => {
  req.files // ...
});
```

You can even decide to use it in a single route(may not look so good though):

```js
app.post('/upload', (req, res) => {
  if (someSetting.version === 'old') {
    res.end('no');
    return;
  }
  formidable()(req, res, function (err, req, res) {
    // ...
  });
```

About using a middleware, please refer to the middleware doc of express.

- http://expressjs.com/en/guide/using-middleware.html

Thanks!
