### ISSUE TITLE
when using in TS projects, cannot import d.ts automatically

### ISSUE THREAD

**Issue by frogcjn** [noraesae/express-formidable#2]
`npm i express-formidable --save'
then
Cannot find module 'express-formidable'

**Comment by noraesae** [comment]
I've not used TS recently. Is there a standard way to include a .d.ts file in a package? If there is, can you provide some information or preferably a PR?

**Comment by frogcjn** [comment]
I think there is a typings in `package.json`
  "typings": "dist/index.d.ts"
See https://github.com/blakeembrey/async-middleware

**Comment by frogcjn** [comment]
Yeah, just need a line in the **package.json**, `"typings": "express-formidable.d.ts"`
I'll make a pull request

**Comment by noraesae** [comment]
Great. Thanks in advance.
