### ISSUE TITLE
Allow multipart and url-encoded encryption types

### ISSUE THREAD

**Issue by JoeChapman** [noraesae/express-formidable#4]
Why do you not allow url-encoded encryption types? If you did, this module could replace Express bodyParser

**Comment by noraesae** [comment]
Thanks for your interests on the library. Will work on this.

**Comment by noraesae** [comment]
Now we support all form types supported by Formidable, including `application/x-www-form-urlencoded`, `application/json`, and `multipart/form-data`. Thanks!
